name: Weekly Update of buildings_data.json to umd_map

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    env: 
      root: .github/api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up environment
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.root }}/requirements.txt

      - name: Run Fetch Availability Script
        run: |
          ls
          python ${{ env.root }}/fetch_availability.py

      # Step 5: Validate buildings_data.json
      - name: Validate buildings_data.json
        run: |
          python -m json.tool buildings_data.json > /dev/null

      - name: Move buildings_data.json
        run: |
          mv buildings_data.json public/buildings_data.json  # Adjust the destination path if different

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add public/buildings_data.json
          git commit -m "Weekly update of buildings_data.json [skip ci]"
          git push origin main
